spring.application.name=booking

# ===============================
# НАЛАШТУВАННЯ HIBERNATE / JPA
# ===============================
# Стратегія роботи з таблицями: update створює таблиці, якщо їх немає, і оновлює їх при зміні Entity
spring.jpa.hibernate.ddl-auto=update
# Вказуємо діалект, щоб Hibernate використовував оптимізовані SQL-команди саме для Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# ЛОГУВАННЯ (ДЛЯ ЗРУЧНОЇ РОЗРОБКИ)
# ===============================
# Виводити всі згенеровані SQL-запити в консоль IntelliJ IDEA
spring.jpa.show-sql=true
# Форматувати SQL-запити, щоб вони були читабельними (з відступами)
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# НАЛАШТУВАННЯ ПІДКЛЮЧЕННЯ
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/booking_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:$hrek}

# ===============================
# НАЛАШТУВАННЯ TELEGRAM БОТА
# ===============================
telegram.bot.username=${BOT_USERNAME:e_bookingbot}
telegram.bot.token=${BOT_TOKEN:8809224193:AAHz_hpQ8AlkQ5YPQlUD0hbERy-YT5LthL}
