spring.application.name=booking
# ===============================
# 1. НАЛАШТУВАННЯ ПІДКЛЮЧЕННЯ
# ===============================
# URL підключення. 5432 - стандартний порт Postgres, booking_db - назва бази
spring.datasource.url=jdbc:postgresql://localhost:5433/booking_db
spring.datasource.username=postgres
spring.datasource.password=$hrek
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 2. НАЛАШТУВАННЯ HIBERNATE / JPA
# ===============================
# Стратегія роботи з таблицями: update створює таблиці, якщо їх немає, і оновлює їх при зміні Entity
spring.jpa.hibernate.ddl-auto=update
# Вказуємо діалект, щоб Hibernate використовував оптимізовані SQL-команди саме для Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 3. ЛОГУВАННЯ (ДЛЯ ЗРУЧНОЇ РОЗРОБКИ)
# ===============================
# Виводити всі згенеровані SQL-запити в консоль IntelliJ IDEA
spring.jpa.show-sql=true
# Форматувати SQL-запити, щоб вони були читабельними (з відступами)
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# НАЛАШТУВАННЯ TELEGRAM БОТА
# ===============================
telegram.bot.username=e_bookingbot
telegram.bot.token=8809224193:AAHz_hpQ8AlkQ5YPQlUD0hbERy-YT5LthLc